agriproject/agriapp/urls.py
from django.urls import path,include
from . import views
app_name='agriapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('agri/<int:agri_id>/',views.detail,name='detail'),
    path('add/',views.add_agri,name='add_agri'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

agriproject/agriproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("agriapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

agriproject/agriapp/models.py
from django.db import models

# Create your models here.
class Agri(models.Model):
    name=models.CharField(max_length=250)
    use=models.TextField()
    About=models.TextField()
    img=models.ImageField(upload_to="gallery")

    def __str__(self):
        return self.name

agriproject/agriapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .form import Agriform
from . models import Agri

# Create your views here.
def index(request):
    agri=Agri.objects.all()
    context={
        'agri_list':agri
    }
    return render(request,'index.html',context)
def detail(request,agri_id):
    ag=Agri.objects.get(id=agri_id)
    return render(request,"detail.html",{'agr':ag})
def add_agri(request):
    if request.method=='POST':
        name=request.POST.get('name')
        use = request.POST.get('use')
        About = request.POST.get('About')
        img = request.FILES['img']
        agri=Agri(name=name,use=use,About=About,img=img)
        agri.save()
    return render(request,"add.html")
def update(request,id):
    agri=Agri.objects.get(id=id)
    form=Agriform(request.POST or None,request.FILES,instance=agri)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'agri':agri})
def delete(request,id):
    if request.method=='POST':
        agri=Agri.objects.get(id=id)
        agri.delete()
        return redirect('/')
    return render(request,'delete.html')

agriproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <br><input type="text" name="name" placeholder="Name of Crop"><br><br>
    <input type="text" name="use" placeholder="Use of Crop"><br><br>
    <input type="text" name="About" placeholder="About the Crop"><br><br>
    <input type="file" name="img"><br><br>
    <input type="submit">
</form>
{% endblock %}

agriproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
        Agriculture
      <a class="btn btn-outline-success" href="{% url 'agriapp:add_agri' %}" type="button">Add</a>
  </a>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

agriproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    <center><h1>Are you want to Delete the Item ?.</h1></center>
    <input type="submit" value="Yes">

</form>

agriproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
  <div class="row">
     <div class="col-md-6"><br>
        <img src="{{agr.img.url}}" width="300" height="300">
     </div>
   <div class="col-md-6"><br>
    <h2>{{agr.name}}</h2>
    <h6>{{agr.use}}<h6><br>
    <i>{{agr.About}}</i><br>
        <a class="btn btn-outline-success" href="{% url 'agriapp:update' agr.id %}" type="button">Update</a>
        <a class="btn btn-danger" href="{% url 'agriapp:delete' agr.id %}" type="button">Delete</a>


   </div>
  </div>
</div>
{% endblock %}

agriproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

agriproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    {% for i in agri_list %}
    <div class="col-md-3">
        <div class="card mt-4">
            <img src="{{i.img.url}}" class="card-img-top"  alt=""  height="200px">
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <a href="{% url 'agriapp:detail' i.id %}" class="btn btn-primary">Explore</a>
        </div>
            <br>
        </div>
    </div>
             {% endfor %}
</div>
{% endblock %}